config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :edit, :create, :new], except: :index do
    resources :doses, only: [:new, :create, :edit]
  end
  resources :doses, only: [:destroy]
end

# GET "cocktails"
# A user can see the details of a given cocktail, with the dose needed for each ingredient
# GET "cocktails/42"
# A user can create a new cocktail
# GET "cocktails/new"
# POST "cocktails"A user can see the list of cocktails
# GET "cocktails"
# A user can see the details of a given cocktail, with the dose needed for each ingredient
# GET "cocktails/42"
# A user can create a new cocktail
# GET "cocktails/new"
# POST "cocktails"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

 def index
  @cocktails = Cocktail.all
 end

   # GET /articles/1
  def show
  @cocktails = Cocktail.all
  @dose = Dose.new
  end

  # GET /articles/new
  def new
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  # GET /articles/1/edit
  def edit

    @cocktails = Cocktail.all
    @cocktail = Cocktail.find(params[:id])

  end

  # POST /cocktail
  def create
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'A new cocktail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    @cocktails = Cocktail.all
    if @cocktail.update(cocktail_params)
      redirect_to @cocktail, notice: 'The cocktail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @cocktails = Cocktail.all
    @cocktail.destroy
    redirect_to root_path, notice: 'The cocktail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy]

  def show
    @cocktails = Cocktail.all
  end

  def new
    @cocktails = Cocktail.all
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def edit
    @cocktails = Cocktail.all
  end

  def create
    @cocktails = Cocktail.all
    @dose = Dose.new(dose_params)
        @cocktail = Cocktail.find(params[:cocktail_id])

    @dose.cocktail = @cocktail
    if @dose.save
      flash[:alert] = "A new dose was created."
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    @cocktails = Cocktail.all
    if @dose.update(dose_params)
      redirect_to @dose, notice: 'The dose was successfully updated.'
    else
      render :new
    end
  end

  def destroy
    @cocktails = Cocktail.all
    @dose.delete
    redirect_to cocktails_url, notice: 'The dose was successfully destroyed.'
  end

  private
    def set_dose
      @dose = Dose.find(params[:id])
    end

    def dose_params
      params.require(:dose).permit(:name, :description, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail, class: 'form') do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/cocktails/edit.html.erb
<h1>edit cocktail</h1>


<% @cocktail.doses.each do |dose|%>
     <ul><li class="list-inline-item"> <%= dose.description  %> </li>
     <li class="list-inline-item"> <%= dose.ingredient.name %> </li></ul>

    <% end %>

  <%= link_to 'Edit', edit_cocktail_path(@cocktail) %>
  <%= link_to 'Cocktails lists', root_path %>

app/views/cocktails/index.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/numama/image/upload/ar_2.5,c_crop/v1603385466/home_banner_du3qqz.png);">
  <div class="container">
    <h1> <strong>Bistrôt les Amis</strong> </h1>
    <p>Change your life and learn to drink more ;-)</p>
    <a class="btn btn-primary" href="/cocktails/new">Create a Cocktail</a>
  </div>
</div>
<br>

<div class="row">
        <% @cocktails.each do |cocktail| %>
         <% if cocktail.photo.attached? %>
            <div class="card col-4">
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
                  <h5 class="card-title"> <%= cocktail.name %> </h5>

                </div>
                <% cocktail.ingredients.each do |ingredient| %>
                <ul class="list-group list-group-flush">

                  <li class="list-group-item">   <%= ingredient.name %> </li>
                </ul>
                <% end %>
                <div class="card-body">
                   <%= link_to 'more infos', cocktail_path(cocktail), class: "btn btn-success" %>
              </div>
            <% end %>
          <% end %>
  </div>

app/views/cocktails/new.html.erb
<h1>create a new cocktail </h1>
  <%= render "form" %>

<%= link_to 'cocktails list', root_path %>

app/views/cocktails/show.html.erb
<h1>Show Cocktail</h1>

<div class="card-product">
  <img src="<%= cl_image_path @cocktail.photo.key %>" />
  <div class="card-product-infos">
    <h2><%= @cocktail.name %></h2>
      <% @cocktail.ingredients.each do |ingredient| %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">   <%= ingredient.name %> </li>
        </ul>
        <% end %>
  </div>
</div>


<% @cocktail.doses.each do |dose|%>
     <ul><li class="list-inline-item"> <%= dose.description  %> </li>
     <li class="list-inline-item"> <%= dose.ingredient.name %> </li></ul>
    <% end %>

    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description  %>
      <%= f.submit class: "btn btn-primary"%>
    <% end %>

  <%= link_to 'Edit', edit_cocktail_path(@cocktail) %>
  <%= link_to 'Cocktails lists', root_path %>

app/views/doses/new.html.erb
<h1> create a dose </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bistrôt Les Amis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-cocktail">
  <a class="navbar-brand" href="#">
    <img src="https://res.cloudinary.com/numama/image/upload/v1603985159/Captura_de_Tela_2020-10-29_a%CC%80s_12.21.03_apayle.png" class="avatar"/>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Cocktails List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% @cocktails.each do |cocktail| %>
         <ul> <%= link_to cocktail.name, cocktail_path(cocktail) %> </ul>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>